### ISSUE TITLE
Add typing information

### ISSUE THREAD

**Issue by bodograumann** [posva/vue-promised#21]
It seems vue-promised is currently a javascript-only library. To use it in projects with `vue-cli-plugin-typescript`, it would be nice to have typing information. My guess is, that the required type file could be quite simple.

Without typing information though, using `import { Promised } from "vue-promised";` in a vue-sfc with `<script lang="ts">` will give a type-checking error:

> Could not find a declaration file for module 'vue-promised'. […]

**Comment by posva** [comment]
If anybody wants to add the d.ts file in src, they can send a PR

**Comment by bodograumann** [comment]
Hey @posva, thanks for having a look at this.
Unfortunately the given types don‘t quite work yet.
Here is the errors I get in my vue-cli project:

- `Generic type 'Promise<T>' requires 1 type argument(s)`; so we need `Promise<any>`.
- `Type 'DefaultComputed' is not generic.`; so leave away the `<never>`
- `'Promised' only refers to a type, but is being used as a value here.` when I try to register the imported component; not sure what exactly needs to be done here.

**Comment by posva** [comment]
should be fixed, I added tests this time. If you find any ts problem, please create a PR, it should be easy to contribute now that tests are there 😉

**Comment by bodograumann** [comment]
Ok, the first two things are fine now, but the last issue still persists.
To be honest I don’t completely understand all the interactions between webpack, npm, the various module formats and type definitions, but I will try to find some time to read up on it and solve the remaining problem.
